name: dart_ssh_two
description: A SSH2 Client library for Dart Lang
version: 0.0.2
author: Alexander Haslam <champhaggy@gmail.com>
homepage: https://github.com/indiealexh/dart-ssh-two

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
